### ISSUE TITLE
ICRM does not work with MultipleShooting

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#8]
When the ICRM option is chosen, I get errors like the following from examples/icrm/3dof/hypersonic3DOF.py: 

`Running Continuation Step #1 :
Starting iteration 1/11
capi_return is NULL
Call-back cb_fcn_in___user__routines failed.
MultipleShooting.py:564: too many values to unpack (expected 7)
Traceback (most recent call last):
  File "d:\users\seanm\documents\beluga development\beluga_dev\beluga\beluga\bvpsol\algorithms\MultipleShooting.py", line 466, in solve
    t,yy = ode45(self.stm_ode_func, tspan, y0stm, paramGuess, aux, arc_idx, abstol=1e-8, reltol=1e-4)
  File "d:\users\seanm\documents\beluga development\beluga_dev\beluga\beluga\integrators\ode45.py", line 40, in ode45

    y_out[ctr, :] = r.integrate(r.t+dt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\integrate\_ode.py", line 432, in integrate
    self.f_params, self.jac_params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\integrate\_ode.py", line 1090, in run
    tuple(self.call_args) + (f_params,)))
  File "d:\users\seanm\documents\beluga development\beluga_dev\beluga\beluga\bvpsol\algorithms\MultipleShooting.py", line 389, in wrapper
    return _stmode_fd(t, _X, p, const, arc_idx)
  File "<string>", line 59, in deriv_func_nojit
ValueError: too many values to unpack (expected 7)
Iteration 1/11 failed to converge!

__init__.py:343: Initial guess should converge for automated continuation to work!!
Traceback (most recent call last):
  File "d:\users\seanm\documents\beluga development\beluga_dev\beluga\beluga\core.py", line 175, in run_continuation_set
    for aux in step:  # Continuation step returns 'aux' dictionary
  File "d:\users\seanm\documents\beluga development\beluga_dev\beluga\beluga\continuation\__init__.py", line 285, in __next__
    return self.next()
  File "d:\users\seanm\documents\beluga development\beluga_dev\beluga\beluga\continuation\__init__.py", line 344, in next
    raise RuntimeError('Initial guess does not converge.')
RuntimeError: Initial guess does not converge.
core.py:220: Exception : Initial guess does not converge.
core.py:221: Stopping
Continuation process completed in 0.2833 seconds.`

**Comment by SeanMatthewNolan** [comment]
It has to do with the storage of `const` in line  389 of MultipleShooting.py. It is stored as a dictionary when an array or list is expected.

**Comment by SeanMatthewNolan** [comment]
I believe I fixed this with my last merge.
